AWSTemplateFormatVersion: 2010-09-09
Description: "aurora.template.yml"

Parameters:
  AppName:
    Type: String
    Default: fastrunner

Resources:
  AuroraDBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora
      EngineMode: serverless
      DatabaseName: !Sub "${AppName}Db"
      ScalingConfiguration:
        AutoPause: true
      MasterUsername:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref DBSecret,
            ":SecretString:DB_USER}}",
          ],
        ]
      MasterUserPassword:
        !Join [
          "",
          [
            "{{resolve:secretsmanager:",
            !Ref DBSecret,
            ":SecretString:DB_PASS}}",
          ],
        ]
      BackupRetentionPeriod: 1
      DeletionProtection: false
      VpcSecurityGroupIds:
        - !ImportValue
          Fn::Sub: "${AppName}-db-security-group-id"
      DBSubnetGroupName: !ImportValue
          Fn::Sub: "${AppName}-db-subnet-group"
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-db"

  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AppName}-dbpassword"
      GenerateSecretString:
        SecretStringTemplate: '{"DB_USER":"admin"}'
        GenerateStringKey: "DB_PASS"
        PasswordLength: 12
        ExcludeCharacters: '"@/\'
      Tags:
        - Key: Name
          Value: !Sub "${AppName}-dbpassword"

Outputs:
  AuroraEndpoint:
    Description: Aurora cluster endpoint
    Value:
      !Join [
        "",
        [
          !GetAtt AuroraDBCluster.Endpoint.Address,
          ":",
          !GetAtt AuroraDBCluster.Endpoint.Port,
        ],
      ]
    Export:
      Name: !Sub "${AppName}-db-endpoint"
  DBSecretArn:
    Value: !Ref DBSecret
    Export:
      Name: !Sub "${AppName}-db-secrets-arn"
